version: '3.3'

services:
  spring-app1:
    image: spring-app1
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/mongodb
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongodata: